//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dadaev_Proekt_
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Authors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AK_Authors()
        {
            this.AK_Books = new HashSet<AK_Books>();
        }
    
        public int Author_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public System.DateTime year_of_birth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AK_Books> AK_Books { get; set; }
    }
}
