//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dadaev_Proekt_
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Book_Publisher
    {
        public int Book_ID { get; set; }
        public int Publisher_ID { get; set; }
        public int ID_Book_Publisher { get; set; }
    
        public virtual AK_Books AK_Books { get; set; }
        public virtual AK_Publishers AK_Publishers { get; set; }
    }
}
