//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dadaev_Proekt_
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Fines
    {
        public int Fine_ID { get; set; }
        public int Fine_Amount { get; set; }
        public string Reason { get; set; }
        public string Paid { get; set; }
        public int Loan_ID { get; set; }
        public int Returned { get; set; }
    }
}
