//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dadaev_Proekt_
{
    using System;
    using System.Collections.Generic;
    
    public partial class AK_Loans
    {
        public int Loan_ID { get; set; }
        public int User_ID { get; set; }
        public int Book_ID { get; set; }
        public System.DateTime Issue_Date { get; set; }
        public System.DateTime Return_Date { get; set; }
    
        public virtual AK_Books AK_Books { get; set; }
        public virtual AK_Users AK_Users { get; set; }
    }
}
