//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dadaev_Proekt_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user97_dbEntities1 : DbContext
    {
        public user97_dbEntities1()
            : base("name=user97_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AK_Authors> AK_Authors { get; set; }
        public virtual DbSet<AK_Book_Publisher> AK_Book_Publisher { get; set; }
        public virtual DbSet<AK_Books> AK_Books { get; set; }
        public virtual DbSet<AK_Fines> AK_Fines { get; set; }
        public virtual DbSet<AK_Genres> AK_Genres { get; set; }
        public virtual DbSet<AK_Loans> AK_Loans { get; set; }
        public virtual DbSet<AK_Publishers> AK_Publishers { get; set; }
        public virtual DbSet<AK_Publishers_soedin> AK_Publishers_soedin { get; set; }
        public virtual DbSet<AK_Role> AK_Role { get; set; }
        public virtual DbSet<AK_Users> AK_Users { get; set; }
    }
}
